version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Map port 5000 on the host to port 80 in the container
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Map port 80 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom Nginx configuration
      - ./dist:/usr/share/nginx/html  # Mount the 'dist' folder from Node.js container
